FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# argument-analysis-research

This project provides a simple repo for analyzing arguments.

## Analyze [/analyze]

### Create analyzed document from input [POST]

You may supply a string of text to analyze and get a document containing segements and extracted keywords.

+ Request (application/json)

        {
            "input": "Hello darkness my old friend"
        }

+ Response 200 (application/json)

    + Body

            {
                "content": "Hello darkness my old friend",
                "segments": [
                    {
                        "text": "Hello darkness my old friend",
                        "keywords": [
                            {
                                "key": "old friend",
                                "value": 4
                            },
                            {
                                "key": "darkness",
                                "value": 1
                            }
                        ]
                    }
                ]
            }