apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adw-data-pvc
  labels:
    component: "adw"
spec:
  storageClassName: ""
  volumeName: adw-data
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 6Gi