apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adw-resources
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
  namespace: research
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 4Gi
