apiVersion: v1
kind: Service
metadata:
  name: "{NAME}"
  labels:
    component: "{NAME}"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    component: "{NAME}"
