apiVersion: v1
kind: PersistentVolume
metadata:
  name: adw-data-config
  labels:
    component: "adw"
    subComponent: "config"
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/adw-data/config
    type: ""

