apiVersion: v1
kind: PersistentVolume
metadata:
  name: adw-data-resources
  labels:
    component: "adw"
    subComponent: "resources"
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/adw-data/resources
    type: ""

