apiVersion: v1
kind: PersistentVolume
metadata:
  name: linker-data
  labels:
    failure-domain.beta.kubernetes.io/zone: "europe-west2-b__europe-west2-c"
    component: "linker"
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/linker-data
    type: ""

