apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adw-data-pvc
  labels:
    component: "adw"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      component: adw